replicaCount: 3

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: petbuddy.party
    # kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cert
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
      }
  hosts:
  - host: petbuddy.party
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: petbuddy-party-tls
    hosts:
    - petbuddy.party
