apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-petbuddy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: charts/petbuddy
    targetRevision: main
    helm:
      valueFiles:
      - "../values/my-petbuddy-values.yaml"
      - "../values/existingsecret.yaml"
